import { Car } from './car';

export const CARS: Car[] = [
  {
    id: 1,
    name: 'BMW 1 Series',
    issuance: 2013,
    picture: '../assets/Logos/bmw.jpg',
    category: ['Coupe', 'Convertible'],
    created: new Date(),
  },
  {
    id: 2,
    name: 'Audi 100',
    issuance: 1994,
    picture: '../assets/Logos/audi.jpg',
    category: ['Wagon', 'Sedan'],
    created: new Date(),
  },
  {
    id: 3,
    name: 'FIAT 124 Spider',
    issuance: 1994,
    picture: '../assets/Logos/fiat.jpg',
    category: ['Convertible'],
    created: new Date(),
  },
  {
    id: 4,
    name: 'Ram 1500 Classic ',
    issuance: 2019,
    picture: '../assets/Logos/ram.jpg',
    category: ['Pickup'],
    created: new Date(),
  },
  {
    id: 5,
    name: 'GMC 1500 Club Coupe',
    issuance: 1999,
    picture: '../assets/Logos/gmc.jpg',
    category: ['Pickup'],
    created: new Date(),
  },
  {
    id: 6,
    name: 'Alfa Romeo	164',
    issuance: 1995,
    picture: '../assets/Logos/alfa.jpg',
    category: ['Sedan'],
    created: new Date(),
  },
  {
    id: 7,
    name: 'Mercedes-Benz	190 E',
    issuance: 1993,
    picture: '../assets/Logos/mercedes.jpg',
    category: ['Sedan'],
    created: new Date(),
  },
  {
    id: 8,
    name: 'Volvo 240',
    issuance: 1993,
    picture: '../assets/Logos/volvo.jpg',
    category: ['Sedan', 'Wagon'],
    created: new Date(),
  },
  {
    id: 9,
    name: 'Saab 3-Sep',
    issuance: 1999,
    picture: '../assets/Logos/saab.jpg',
    category: ['Hatchback', 'Convertible'],
    created: new Date(),
  },
  {
    id: 10,
    name: 'Chrysler 300',
    issuance: 2019,
    picture: '../assets/Logos/chrysler.jpg',
    category: ['Sedan'],
    created: new Date(),
  },
  {
    id: 11,
    name: 'Nissan Xterra',
    issuance: 2010,
    picture: '../assets/Logos/nissan.jpg',
    category: ['SUV'],
    created: new Date(),
  },
];
